# Generated by /feature-spec
# Feature: FastAPI Base Project
# Stack: python
# Assumptions: 3 (see fastapi-base-project_assumptions.yaml)
# Generated: 2026-03-06T00:00:00Z

@fastapi-base-project
Feature: FastAPI Base Project
  As a developer
  I want a production-structured FastAPI application with health endpoints,
    structured logging, correlation IDs, and Pydantic settings
  So that I have a solid foundation for building features with a fully
    passing test suite and zero external dependencies

  Background:
    Given the application is running with default settings

  # ━━ GROUP A: Key Examples ━━

  # Why: Core health endpoint — defines the primary health check response shape
  @key-example @smoke
  Scenario: Health endpoint returns application status
    When I request the health endpoint
    Then the request should succeed
    And the response should contain the application status as "ok"
    And the response should contain the application version
    And the response should contain the current environment

  # Why: Liveness probe — must always indicate the process is alive
  @key-example @smoke
  Scenario: Liveness probe indicates the application is alive
    When I request the liveness endpoint
    Then the request should succeed
    And the response should indicate the application is alive

  # Why: Readiness probe — in this base configuration, always ready
  @key-example @smoke
  Scenario: Readiness probe indicates the application is ready
    When I request the readiness endpoint
    Then the request should succeed
    And the response should indicate the application is ready

  # Why: Correlation ID generation — establishes traceability for requests without a provided ID
  @key-example @smoke
  Scenario: A correlation ID is generated when none is provided
    When I send a request without a correlation ID header
    Then the response should include a correlation ID header
    And the correlation ID should be a valid UUID

  # Why: Correlation ID passthrough — callers can propagate their own trace ID
  @key-example @smoke
  Scenario: A caller-provided correlation ID is preserved
    When I send a request with the correlation ID "abc-123"
    Then the response should include the correlation ID "abc-123"

  # Why: Structured JSON logging — validates log output is machine-parseable with correlation context
  @key-example
  Scenario: Structured JSON logging includes the correlation ID
    Given the application is configured with JSON log format
    When I send a request
    Then the log output should be valid JSON
    And the log entry should include a correlation ID field
    And the log entry should include a timestamp
    And the log entry should include a log level

  # Why: App factory pattern — settings injection works cleanly without environment patching
  @key-example
  Scenario: The application is created with custom settings
    Given I create the application with a custom environment setting of "production"
    When I request the health endpoint
    Then the response should report the environment as "production"

  # ━━ GROUP B: Boundary Conditions ━━

  # Why: Each valid environment value must be accepted — enumerated boundary
  @boundary
  Scenario Outline: Health endpoint reflects each valid environment setting
    Given the application is configured with environment "<environment>"
    When I request the health endpoint
    Then the response should report the environment as "<environment>"

    Examples:
      | environment |
      | development |
      | staging     |
      | production  |

  # Why: Each valid log level must be accepted — enumerated boundary
  @boundary
  Scenario Outline: Application starts successfully with each valid log level
    Given the application is configured with log level "<level>"
    When the application starts
    Then the application should initialise without errors

    Examples:
      | level   |
      | DEBUG   |
      | INFO    |
      | WARNING |
      | ERROR   |

  # Why: Both log formats must produce output in their expected format
  @boundary
  Scenario Outline: Log output matches the configured format
    Given the application is configured with log format "<format>"
    When I send a request
    Then the log output should be in "<format>" format

    Examples:
      | format |
      | json   |
      | text   |

  # [ASSUMPTION: confidence=medium] Empty correlation ID header is treated as absent
  # Why: Empty string correlation ID is a boundary — system should treat it as absent
  @boundary
  Scenario: An empty correlation ID header is treated as absent
    When I send a request with an empty correlation ID header
    Then the response should include a generated correlation ID
    And the correlation ID should be a valid UUID

  # Why: API prefix boundary — all routes must be under the configured prefix
  @boundary
  Scenario: All endpoints are served under the configured API prefix
    Given the application is configured with API prefix "/v1"
    When I request the health endpoint at "/v1/health"
    Then the request should succeed

  # ━━ GROUP C: Negative Cases ━━

  # Why: Unknown routes must return structured JSON errors, not HTML
  @negative @smoke
  Scenario: An unknown route returns a JSON error
    When I request a route that does not exist
    Then the response should indicate the resource was not found
    And the response body should be JSON, not HTML

  # Why: Invalid environment value should be rejected at startup
  @negative
  Scenario: An invalid environment value is rejected
    When I attempt to create the application with environment "invalid-env"
    Then the application should fail to initialise
    And the error should indicate an invalid environment value

  # Why: Invalid log level should be rejected at startup
  @negative
  Scenario: An invalid log level is rejected
    When I attempt to create the application with log level "TRACE"
    Then the application should fail to initialise
    And the error should indicate an invalid log level

  # Why: Invalid log format should be rejected at startup
  @negative
  Scenario: An invalid log format is rejected
    When I attempt to create the application with log format "xml"
    Then the application should fail to initialise
    And the error should indicate an invalid log format

  # [ASSUMPTION: confidence=high] FastAPI returns 405 for unsupported methods on defined routes
  # Why: Ensures non-GET methods are rejected on health endpoints
  @negative
  Scenario: Health endpoint rejects unsupported HTTP methods
    When I send a POST request to the health endpoint
    Then the response should indicate the method is not allowed

  # ━━ GROUP D: Edge Cases ━━

  # Why: Correlation ID uniqueness — two requests without IDs should get different traces
  @edge-case
  Scenario: Each request without a correlation ID receives a unique ID
    When I send two consecutive requests without correlation ID headers
    Then each response should contain a different correlation ID

  # [ASSUMPTION: confidence=low] Maximum correlation ID length is 500 characters
  # Why: Very long correlation ID — system should not truncate or reject caller-provided values
  @edge-case
  Scenario: A very long correlation ID is preserved without truncation
    When I send a request with a correlation ID of 500 characters
    Then the response should include the same 500-character correlation ID

  # Why: Default settings with no environment variables — the zero-config path must work
  @edge-case @smoke
  Scenario: All tests pass with no environment variables set
    Given no environment variables are set
    When the full test suite is executed
    Then all tests should pass using default settings

  # Why: Custom version reflects in health — confirms settings injection for version field
  @edge-case
  Scenario: Health endpoint reflects a custom application version
    Given I create the application with version "2.5.0"
    When I request the health endpoint
    Then the response should report the version as "2.5.0"

  # Why: Text log mode for local development — ensure human-readable output
  @edge-case
  Scenario: Text log format produces human-readable output
    Given the application is configured with text log format
    When I send a request
    Then the log output should be human-readable, not JSON

  # ━━ GROUP D (continued): Edge Case Expansion — Security, Concurrency, Integration ━━

  # Why: Security — injection characters in correlation ID must not cause harm
  @edge-case
  Scenario: Correlation ID with special characters is handled safely
    When I send a request with the correlation ID "<script>alert(1)</script>"
    Then the response should include the correlation ID in the header
    And no script execution or injection should occur

  # Why: Security — malformed content-type must not crash the application
  @edge-case
  Scenario: Malformed content-type header is handled gracefully
    When I send a request with a malformed content-type header
    Then the application should respond without crashing
    And the response should be valid JSON

  # Why: Concurrency — each concurrent request gets its own trace
  @edge-case
  Scenario: Concurrent requests receive independent correlation IDs
    When I send 10 concurrent requests without correlation ID headers
    Then each response should contain a unique correlation ID

  # Why: Concurrency — context isolation ensures no ID leakage between requests
  @edge-case
  Scenario: Correlation ID context does not leak between requests
    When I send a request with correlation ID "request-A"
    And I then send a request without a correlation ID header
    Then the second response should not contain "request-A"
    And the second response should contain a freshly generated correlation ID

  # Why: Integration — JSON logging must work without a TTY (CI/CD, pipes)
  @edge-case
  Scenario: JSON logging works when output is piped
    Given the application is configured with JSON log format
    And the output is not connected to a terminal
    When I send a request
    Then the log output should still be valid JSON

  # Why: Integration — no warm-up gap; the app must handle requests immediately
  @edge-case
  Scenario: Application handles requests immediately after startup
    Given the application has just started
    When I send a request immediately
    Then the request should succeed
